// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asmsmtujsfndtvsqdcwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbXNtdHVqc2ZuZHR2c3FkY3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzYxNTksImV4cCI6MjA3NDIxMjE1OX0.Er7lu4p7EmDgJhNGZlM0qrRF5l5CmQ8_pMcMVEQhrBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});